SUPABASE_URL = "https://qtayzkwelmrltrxgcoie.supabase.co"
SUPABASE_DB_URL = "postgresql://postgres.qtayzkwelmrltrxgcoie:2Sv05101710**@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0YXl6a3dlbG1ybHRyeGdjb2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTYyMjEsImV4cCI6MjA2NzgzMjIyMX0.eR8ywE99kqL5O29faRYCEvmt9NC04ov1BjOILZQk_-g"
